--------ALL_VENDTRANS--------
---DUP CHECK
SELECT COUNT(FCTEXCLHOTELSSALESID) AS COUNT_OF_SALE, COUNT(DISTINCT FCTEXCLHOTELSSALESID) AS COUNT_DISTINCT_OF_SALE,
    COUNT(FCTEXCLHOTELSSALESID) - COUNT(DISTINCT FCTEXCLHOTELSSALESID) AS DIFF
FROM COLES_CLEAN.LIQUORLAND_MERCH.ALL_FCTEXCLHOTELSSALES;