--------ALL_VENDPACKINGSLIPTRANS--------
---MISSING CHECK
SELECT to_char(DELIVERYDATE,'YYYY-MM') trans_month, count(*) trans_count
FROM COLES_CLEAN.LIQUORLAND_MERCH.ALL_VENDPACKINGSLIPTRANS
WHERE DELIVERYDATE >= '2021-01-01'
GROUP BY trans_month
ORDER BY trans_month;
