---MISSING CHECK
SELECT to_char(DATEPHYSICAL,'YYYY-MM') trans_month, count(*) trans_count
FROM COLES_CLEAN.LIQUORLAND_MERCH.ALL_INVENTTRANS
WHERE DATEPHYSICAL >= '2021-01-01'
GROUP BY trans_month
ORDER BY trans_month;