-----------CD-----------
CREATE OR REPLACE TABLE COLES.LIQUORLAND.CD
AS
SELECT
CD.STATE,
CD.BRANDID,
CD.DESCRIPTION,
CD.STARTDATE,
CD.ENDDATE,
CD.REBATESCANLINE,
CD.REBATENO,
CD.ITEMID,
CD.UNITOFMEASURE,
CD.CRITERIA,
CD.REBATEREFID,
CD.REFTABLEID,
CD.REFRECID,
CD.REBATEPOSTED,
CD.CLAIMREFID,
CD.CLAIMTABLEID,
CD.PRODUCTCATEGORY,
CD.REVERSALCLAIMREFID,
CD.CLM_PER_UNIT,
CD.CLM_QTY,
CD.CLM_VAL,
CD.CD_TYPE,
CD.REBATE_ENTITLEMENT_NUM,
CD.MULTIPLIER_NUM,
CD.ENTITLEMENT_AMT,
CD.CLM_WET,
CD.REBATESCANCLASS,
CD.REVERSED,
CD.ENDVENDACCOUNT AS VENDOR_NUMBER,
VD.NM AS VENDOR_NAME
FROM COLES.LIQUORLAND.VIEW_CD_RAW CD
LEFT JOIN COLES_CLEAN.LIQUORLAND_MERCH.ALL_LIQ_REBATELINE RL
ON CD.REBATENO = RL.REBATENO
LEFT JOIN (SELECT DISTINCT ACCOUNTNUMBER, "Name" AS NM FROM COLES_CLEAN.LIQUORLAND_MERCH.ALL_DIMVENDOR
            WHERE UPPER(CURRENTRECORD) = 'CURRENT RECORD') VD
ON CD.ENDVENDACCOUNT = VD.ACCOUNTNUMBER
WHERE ENDDATE >= '2020-01-01'
ORDER BY VENDOR_NAME, CD_TYPE, DESCRIPTION, STARTDATE, ENDDATE, REBATENO, REBATE_ENTITLEMENT_NUM, BRANDID, STATE;
--2M31S