-----------CD_FULL-----------
CREATE OR REPLACE TABLE COLES.LIQUORLAND.CD_FULL
AS
SELECT
CD.STATE,
CD.BRANDID,
CD.DESCRIPTION,
CD.STARTDATE,
CD.ENDDATE,
CD.REBATESCANLINE,
CD.REBATENO,
CASE WHEN (TRIM(CD.ITEMID) = '' OR CD.ITEMID IS NULL) THEN RB.ITEMRELATION ELSE CD.ITEMID END AS ITEMID,
CD.UNITOFMEASURE,
CD.CRITERIA,
CD.REBATEREFID,
CD.REFTABLEID,
CD.REFRECID,
CD.REBATEPOSTED,
CD.CLAIMREFID,
CD.CLAIMTABLEID,
CD.PRODUCTCATEGORY,
CASE WHEN (TRIM(CD.REVERSALCLAIMREFID) = '' OR CD.REVERSALCLAIMREFID IS NULL) THEN RV.REVERSALCLAIMREFID ELSE CD.REVERSALCLAIMREFID END AS REVERSALCLAIMREFID,
CD.CLM_PER_UNIT,
CD.CLM_QTY,
CD.CLM_VAL,
CD.CD_TYPE,
CD.REBATE_ENTITLEMENT_NUM,
CD.MULTIPLIER_NUM,
CD.ENTITLEMENT_AMT,
CD.CLM_WET,
CD.REBATESCANCLASS,
CD.REVERSED,
CD.VENDOR_NUMBER,
CD.VENDOR_NAME
FROM (SELECT * FROM COLES.LIQUORLAND.CD
        UNION ALL
        SELECT * FROM COLES.LIQUORLAND.CD_NO_INFO) CD
LEFT JOIN COLES_CLEAN.LIQUORLAND_MERCH.ALL_LIQ_REBATETABLE RB
ON CD.REBATENO = RB.REBATENO
LEFT JOIN (SELECT DISTINCT REBATENO, CLAIMREFID, REVERSALCLAIMREFID FROM 
        (SELECT * FROM COLES.LIQUORLAND.CD
        UNION ALL
        SELECT * FROM COLES.LIQUORLAND.CD_NO_INFO) T
        WHERE REVERSALCLAIMREFID IS NOT NULL AND TRIM(REVERSALCLAIMREFID) <> '') RV
ON CD.REBATENO = RV.REBATENO
AND CD.CLAIMREFID = RV.CLAIMREFID;