-----------CD_MISMATCH-----------
CREATE OR REPLACE TABLE COLES.LIQUORLAND.CD_MISMATCH
AS
(WITH CD_MISMATCH_1
AS
(SELECT CD.*, CH.UNITID
FROM COLES.LIQUORLAND.CD_MISSING_QTY CD
LEFT JOIN (SELECT DISTINCT REBATENO, UNITID FROM COLES_CLEAN.LIQUORLAND_MERCH.ALL_LIQ_REBATETABLE) CH
ON CD.REBATENO = CH.REBATENO
WHERE UPPER(CD.CD_TYPE) LIKE '%SCAND%'
AND CD.ENDDATE >= '2021-10-01'),
CD_MISMATCH_2 AS
(SELECT
CD.STATE,
CD.BRANDID,
CD.DESCRIPTION,
CD.STARTDATE,
CD.ENDDATE,
CD.REBATENO,
CD.CD_TYPE,
CD.ITEMID,
CD.CLM_VAL,
CD.AGV_SALE_PRICE,
CD.AVG_ITEMPRICE_INC,
CD.CLM_QTY,
CD.SLS_QTY,
CD.PH_VAL,
CD.PROMO_QTY,
CD.CLM_QTY_TTL,
CD.VAR_QTY_SLS,
CD.VAR_QTY_PROMO,
CD.VAR_AMT_SLS,
CD.VAR_AMT_PROMO,
CASE WHEN TRIM(CD.UNITID) = '' THEN 0 ELSE U.UOM_QTY END AS UNITOFMEASURE,
CD.MULTIPLIER_NUM,
--SPECIFY MANUALLY
CASE WHEN DESCRIPTION NOT LIKE '%>%' THEN 0
WHEN TRIM(SPLIT_PART(DESCRIPTION, '>', 2)) IN 
('national','fy23 h1','WINE','VIN','VC','National','Nat','NON','NAT','LL','LD','FeverTree200ml','FCLM','Everyday','1C') THEN 0
WHEN DESCRIPTION  LIKE '%ACTBeer%' THEN split_part(TRIM(SPLIT_PART(DESCRIPTION, '>', 2)),'ACTBeer',1)
ELSE SPLIT_PART(DESCRIPTION, '>', 2)::NUMBER(38,2) END AS SCAN_RATE_DESCRIPTION,
CD.REBATE_ENTITLEMENT_NUM
FROM CD_MISMATCH_1 CD
LEFT JOIN COLES.LIQUORLAND.UNITOFMEASURE_TRANSLATE U
ON TRIM(UPPER(CD.UNITID)) = TRIM(UPPER(U.UNITOFMEASURE)))
SELECT *
FROM
(SELECT
CD.*,
CASE WHEN (CD.UNITOFMEASURE - CD.MULTIPLIER_NUM) = 0 THEN 'NO' ELSE 'YES' END AS GAP_UOM,
CASE WHEN (CD.SCAN_RATE_DESCRIPTION - CD.REBATE_ENTITLEMENT_NUM) = 0 THEN 'NO' ELSE 'YES' END AS GAP_SCAN
FROM CD_MISMATCH_2 CD) A
WHERE GAP_UOM = 'YES' OR GAP_SCAN = 'YES');
