-----------CD_TRANSACTIONS-----------
CREATE OR REPLACE TABLE COLES.LIQUORLAND.CD_TRANSACTIONS
AS
SELECT
STARTDATE,ENDDATE,REBATENO,BRANDID,STATE,ITEMID,CRITERIA,
SUM(CLAIMBASE) AS CLAIMBASE,SUM(CLAIMAMOUNT) AS CLAIMAMOUNT,CLAIMAMOUNT_TTL,
ENTITLEMENTAMOUNT,CLAIMREFID,LEDGERJOURNALID,DATAAREAID,REBATEPOSTED,REVERSED,INVOICEID,LEDGERJOURNALIDORIG,CLAIMROSTER,MARKETINGMONEY,
UNITID,MULTIPLIER,REBATEENTITLEMENT,STARTDATE_TABLE,ENDDATE_TABLE,DESCRIPTION,ENDVENDACCOUNT,ITEMRELATION,ITEMRELATIONNAME,ITEMGROUPID
FROM COLES.LIQUORLAND.VIEW_CD_TRANSACTIONS
GROUP BY
STARTDATE,ENDDATE,REBATENO,BRANDID,STATE,ITEMID,CRITERIA,CLAIMAMOUNT_TTL,ENTITLEMENTAMOUNT,CLAIMREFID,LEDGERJOURNALID,DATAAREAID,
REBATEPOSTED,REVERSED,INVOICEID,LEDGERJOURNALIDORIG,CLAIMROSTER,MARKETINGMONEY,UNITID,MULTIPLIER,REBATEENTITLEMENT,STARTDATE_TABLE,
ENDDATE_TABLE,DESCRIPTION,ENDVENDACCOUNT,ITEMRELATION,ITEMRELATIONNAME,ITEMGROUPID
ORDER BY REBATENO;