-----------COST_HISTORY_STATE-----------
CREATE OR REPLACE TABLE COLES.LIQUORLAND.COST_HISTORY_STATE
AS
SELECT
ITEMIDSKU,
UNITOFMEASURE,
FROMDATE,
TODATE,
CH_VAL,
CH_VAL_UNIT,
STATE,
BRANDID
FROM COLES.LIQUORLAND.VIEW_COST_HISTORY_STORE
GROUP BY
ITEMIDSKU,
UNITOFMEASURE,
FROMDATE,
TODATE,
CH_VAL,
CH_VAL_UNIT,
STATE,
BRANDID;