-----------ITEM_SALES-----------
CREATE OR REPLACE TABLE COLES.LIQUORLAND.ITEM_SALES AS
SELECT DISTINCT ITEMIDSKU::VARCHAR AS ITEMIDSKU,
TRIM(UPPER(FIRST_VALUE(ITEMNAME) OVER (PARTITION BY ITEMIDSKU ORDER BY LENGTH(ITEMNAME) DESC))) AS ITEMNAME
FROM COLES_CLEAN.LIQUORLAND_MERCH.ALL_DIMSALEITEM
ORDER BY ITEMIDSKU;