-----------PRICE_HISTORY_STATE-----------
CREATE OR REPLACE TABLE COLES.LIQUORLAND.PRICE_HISTORY_STATE AS
SELECT
ITEMRELATION::VARCHAR(20) AS ITEMIDSKU,
UNITID::VARCHAR(10) AS UNITOFMEASURE,
FROMDATE,
TODATE,
CH_VAL::NUMBER AS PH_VAL,
STATE::VARCHAR(60) AS STATE,
BRANDID::VARCHAR(10) AS BRANDID
FROM COLES.LIQUORLAND.PRICE_HISTORY_STORE
GROUP BY
ITEMRELATION,
UNITID,
FROMDATE,
TODATE,
CH_VAL,
STATE,
BRANDID;