-----------PRICE_HISTORY_CD_MAP-----------

CREATE OR REPLACE TABLE COLES.LIQUORLAND.PRICE_HISTORY_CD_MAP AS
SELECT ITEMIDSKU, B.UOM_QTY, FROMDATE::DATE AS FROMDATE, TODATE::DATE AS TODATE, PH_VAL, TRIM(STATE) AS STATE, TRIM(BRANDID) AS BRANDID
FROM COLES.LIQUORLAND.PRICE_HISTORY_STATE A
LEFT JOIN COLES.LIQUORLAND.UNITOFMEASURE_TRANSLATE B
ON TRIM(UPPER(A.UNITOFMEASURE::VARCHAR)) = TRIM(UPPER(B.UNITOFMEASURE::VARCHAR));

