-----------PRICE_HISTORY_STORE-----------
CREATE OR REPLACE TABLE COLES.LIQUORLAND.PRICE_HISTORY_STORE AS
SELECT CH.*, L.ADDRESSSTATE AS STATE, B.BRANDID
FROM COLES.LIQUORLAND.VIEW_PH CH
LEFT JOIN (SELECT *
        FROM COLES_CLEAN.LIQUORLAND_MERCH.ALL_DIMSTORE
        WHERE UPPER(CURRENTRECORD) = 'CURRENT RECORD') L
        ON CH.STOREID=L.STOREID
LEFT JOIN COLES_CLEAN.LIQUORLAND_MERCH.ALL_DIMBRAND B
ON L.DIMBRANDID=B.DIMBRANDID;