----------PRODUCT_HIERARCHY-----------
CREATE OR REPLACE TABLE COLES.LIQUORLAND.PRODUCT_HIERARCHY AS
SELECT
DIMSALEITEMID,
ITEMIDSKU,
UPPER(UNITOFMEASURE) AS UNITOFMEASURE,
UPPER(ITEMNAME) AS ITEMNAME,
ITEMGROUP,
ITEMBARCODE,
ITEMCATEGORYGROUPINGID,
ITEMCATEGORYID,
ITEMSUBCATEGORYGROUPINGID,
SUBCATEGORYID,
ITEMCLASSID,
SELLITEMID,
ROW_NUM AS RN
FROM
(SELECT
DIMSALEITEMID,
ITEMIDSKU,
UPPER(UNITOFMEASURE) AS UNITOFMEASURE,
UPPER(ITEMNAME) AS ITEMNAME,
ITEMGROUP,
ITEMBARCODE,
ITEMCATEGORYGROUPINGID,
ITEMCATEGORYID,
ITEMSUBCATEGORYGROUPINGID,
SUBCATEGORYID,
ITEMCLASSID,
SELLITEMID,
ROW_NUMBER() OVER (PARTITION BY ITEMIDSKU, UPPER(UNITOFMEASURE) ORDER BY ITEMIDSKU, UPPER(UNITOFMEASURE), ROWEFFECTIVEFROM DESC) AS ROW_NUM
FROM COLES_CLEAN.LIQUORLAND_MERCH.ALL_DIMSALEITEM)
WHERE ROW_NUM = '1'
ORDER BY ITEMNAME;