-----------PROMO_DETAILS-----------
CREATE OR REPLACE TABLE COLES.LIQUORLAND.PROMO_DETAILS
AS
WITH TEMP_PROMOS_WITH_MULTIPLE_UOM
AS
(SELECT DISTINCT DIMPROMOPRICEADVDISC1ID
FROM (
SELECT
DIMPROMOPRICEADVDISC1ID,
ITEMIDSKU,
STATE,
BRANDID,
MIN(UNITOFMEASURE) AS UOM1,
MAX(UNITOFMEASURE) AS UOM2
FROM COLES.LIQUORLAND.VIEW_PD_SALES
WHERE DIMPROMOPRICEADVDISC1ID <> '0'
GROUP BY DIMPROMOPRICEADVDISC1ID, ITEMIDSKU, STATE, BRANDID
HAVING MIN(UNITOFMEASURE) <> MAX(UNITOFMEASURE)) T)
SELECT PD.*,
S.SUM_VAL AS SLS_VAL,
S.SUM_QTY AS SLS_QTY,
'MATCHED ON UOM'::VARCHAR(20) AS UOM_MATCH_IND
FROM COLES.LIQUORLAND.VIEW_PROMO_DETAIL PD
LEFT JOIN COLES.LIQUORLAND.VIEW_PD_SALES S
ON PD.ITEMIDSKU = S.ITEMIDSKU
AND UPPER(PD.UNITOFMEASURE) = UPPER(S.UNITOFMEASURE)
AND TRIM(PD.BRANDID) = TRIM(S.BRANDID)
AND TRIM(PD.STATE) = TRIM(S.STATE)
AND PD.PROMOID::VARCHAR = S.DIMPROMOPRICEADVDISC1ID::VARCHAR
WHERE PROMOID IN (SELECT DIMPROMOPRICEADVDISC1ID AS PROMOID FROM TEMP_PROMOS_WITH_MULTIPLE_UOM)
UNION ALL
SELECT
PD.*,
S.SUM_VAL AS SLS_VAL,
S.SUM_QTY AS SLS_QTY,
'NOT MATCHED ON UOM'::VARCHAR(20) AS UOM_MATCH_IND
FROM COLES.LIQUORLAND.VIEW_PROMO_DETAIL PD
LEFT JOIN COLES.LIQUORLAND.VIEW_PD_SALES S
ON PD.ITEMIDSKU=S.ITEMIDSKU --AND UPPER(PD.UNITOFMEASURE)=UPPER(S.UNITOFMEASURE)
AND PD.BRANDID=S.BRANDID AND PD.STATE=S.STATE
AND PD.PROMOID::VARCHAR=S.DIMPROMOPRICEADVDISC1ID::VARCHAR
WHERE PD.PROMOID::VARCHAR NOT IN (SELECT DIMPROMOPRICEADVDISC1ID::VARCHAR AS PROMOID FROM TEMP_PROMOS_WITH_MULTIPLE_UOM)
;