-----------SALES_ALL_FINAL-----------
CREATE OR REPLACE TABLE COLES.LIQUORLAND.SALES_ALL_FINAL AS
SELECT
UPPER(ITEMNAME) AS ITEMNAME,
ITEMIDSKU,
UPPER(UNITOFMEASURE) AS UNITOFMEASURE,
STATE,
STOREBRANDID AS BRANDID,
DATE1,
SUM(ITEMQUANTITY) AS ITEMQUANTITY,
ITEMPRICE AS ITEMPRICE_INC,
SUM(TOTALLINEDISCOUNTS) AS TOTALLINEDISCOUNTS,
SUM(TOTALLINESALE) AS TOTALLINESALE_EX,
SUM(TOTALLINECOGS) AS TOTALLINECOGS,
ACCOUNTNUMBER AS VENDOR_NUMBER,
VENDOR_NAME, SALETRANSACTIONNUMBER, SALETRANSACTIONLINENUMBER,
P.CAMPAIGNPROMOID, P.PROMOADVDISCACTIONVALUE, P.PROMOPRICESITEMSALESPRICE, P.PROMOADVDISCOUNTNAME,
DIMFLYBUYSID, DIMTEAMMEMBERID, TEAMMEMBERDISCOUNT, WINECLUBCARDNUMBER
FROM COLES.LIQUORLAND.RAW_SALES S
LEFT JOIN COLES_CLEAN.LIQUORLAND_MERCH.ALL_DIMPROMOPRICESADVDISCOUNT P
ON S.DIMPROMOPRICEADVDISC1ID = P.DIMPROMOPRICESADVDISCOUNTID
WHERE DATE1 >= '2021-01-01'
GROUP BY
ITEMNAME,
ITEMIDSKU,
UPPER(UNITOFMEASURE),
STATE,
STOREBRANDID,
DATE1,
ITEMPRICE,
ACCOUNTNUMBER,
VENDOR_NAME,
SALETRANSACTIONNUMBER, SALETRANSACTIONLINENUMBER,
P.CAMPAIGNPROMOID, P.PROMOADVDISCACTIONVALUE, P.PROMOPRICESITEMSALESPRICE, P.PROMOADVDISCOUNTNAME,
DIMFLYBUYSID, DIMTEAMMEMBERID, TEAMMEMBERDISCOUNT, WINECLUBCARDNUMBER; ---17M44S