-----------SCHEMA_PRODUCTS-----------
CREATE OR REPLACE TABLE COLES.LIQUORLAND.SCHEMA_PRODUCTS
AS
SELECT
ITEMIDSKU,
UNITOFMEASURE,
ITEMNAME,
ROW_NUM AS DUMMY
FROM (SELECT
    TRIM(ITEMIDSKU) AS ITEMIDSKU,
    TRIM(UPPER(UNITOFMEASURE)) AS UNITOFMEASURE,
    UPPER(ITEMNAME) AS ITEMNAME,
    ROW_NUMBER() OVER (PARTITION BY TRIM(ITEMIDSKU), TRIM(UPPER(UNITOFMEASURE))
    ORDER BY TRIM(ITEMIDSKU), TRIM(UPPER(UNITOFMEASURE)), DATECREATED DESC) AS ROW_NUM
    FROM COLES_CLEAN.LIQUORLAND_MERCH.ALL_DIMSALEITEM) T
WHERE ROW_NUM = '1' AND UPPER(ITEMNAME) NOT IN
('DO NOT USE', 'DUMMY DO NOT DELETE', 'DO NOT TOUCH', 'DUMMY ITEM DO NOT USE OR DELETE', 'DUMMY 1', 'DUMMY - DO NOT USE', 'DUMMY DO NOT USE');