-----------SLS_QTY-----------
CREATE OR REPLACE TABLE COLES.LIQUORLAND.SLS_QTY
AS
SELECT S.DATE1, S.ITEMIDSKU, UPPER(S.ITEMNAME) AS ITEMNAME, S.BRANDID, S.UNITOFMEASURE, U.UOM_QTY, S.STATE,
AVG(ITEMPRICE_INC) AS ITEMPRICE_INC,
AVG(ITEMPRICE_INC)/1.1 AS ITEMPRICE_EX,
SUM(TOTALLINESALE_EX) AS TOTALLINESALE_EX,
SUM (ITEMQUANTITY) AS ITEMQUANTITY,
CASE WHEN SUM (ITEMQUANTITY) = 0 THEN 0 ELSE SUM(TOTALLINESALE_EX)/SUM (ITEMQUANTITY) END AS AGV_SALE_PRICE,
SUM(TOTALLINEDISCOUNTS) AS TOTALLINEDISCOUNTS,
--SUM(TOTALLINESALE_EX) AS TOTALLINESALE_EX,
SUM(TOTALLINECOGS) AS TOTALLINECOGS
FROM COLES.LIQUORLAND.SALES_ALL_FINAL S
LEFT JOIN COLES.LIQUORLAND.UNITOFMEASURE_TRANSLATE U
ON S.UNITOFMEASURE = U.UNITOFMEASURE
WHERE S.DATE1 >= '2021-01-01'
GROUP BY
S.DATE1,S.ITEMIDSKU,S.ITEMNAME,S.BRANDID,S.UNITOFMEASURE,S.STATE,U.UOM_QTY
ORDER BY S.ITEMIDSKU, S.DATE1, S.STATE;