-----------STATE_BRAND-----------
CREATE OR REPLACE TABLE COLES.LIQUORLAND.STATE_BRAND
AS
SELECT * FROM COLES.LIQUORLAND.LIQUOR_20210101_20221031_STATE_BRAND
UNION ALL
SELECT * FROM
	(SELECT * FROM
		(SELECT DISTINCT STOREID, STATE, BRANDID FROM COLES.LIQUORLAND.VIEW_DIMSTORE
		WHERE STOREID NOT IN (SELECT DISTINCT STOREID FROM COLES.LIQUORLAND.LIQUOR_20210101_20221031_STATE_BRAND)
		ORDER BY STOREID)
	WHERE STOREID||BRANDID <> '70781C'
	AND STOREID||BRANDID <> '70791C');