-----------VENDOR_FROM_SALES-----------
CREATE OR REPLACE TABLE COLES.LIQUORLAND.VENDOR_FROM_SALES
AS
SELECT
ITEMIDSKU,
STATE,
BRANDID,
DIMVENDORID,
VENDOR_NAME,
REPLACE(REPLACE(VENDOR_NAME, CHR(39), ''),'/','') AS VENDOR_NAME2
FROM (
SELECT
ITEMIDSKU,
V.STATE,
BRANDID,
V.DIMVENDORID,
V2."Name" AS VENDOR_NAME,
SLS_QTY,
SLS_VAL,
ROW_NUMBER() OVER (PARTITION BY ITEMIDSKU, V.STATE, BRANDID ORDER BY ITEMIDSKU, V.STATE, BRANDID, SLS_VAL DESC) AS ROW_NUM
FROM COLES.LIQUORLAND.VIEW_SLS_VENDOR V
LEFT JOIN COLES_CLEAN.LIQUORLAND_MERCH.ALL_DIMVENDOR V2
ON V.DIMVENDORID=V2.DIMVENDORID
WHERE V.DIMVENDORID <> 1 AND UPPER(V2."Name") NOT LIKE '%DELETE%' AND V.ITEMIDSKU IS NOT NULL) T WHERE ROW_NUM='1';