-----------VENDOR_PACKING-----------
CREATE OR REPLACE TABLE COLES.LIQUORLAND.VENDOR_PACKING
AS
SELECT A.*, B.ORDERACCOUNT, B.INVOICEACCOUNT 
FROM COLES_CLEAN.LIQUORLAND_MERCH.ALL_VENDPACKINGSLIPTRANS A
LEFT JOIN COLES_CLEAN.LIQUORLAND_MERCH.ALL_VENDPACKINGSLIPJOUR B
ON A.PACKINGSLIPID = B.PACKINGSLIPID
WHERE A.DELIVERYDATE >= '2021-01-01'; --22M